config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'


  resources :supplier_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :supplier_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :repertory_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :repertory_dbs, only: [:index, :update] do
    collection do
      get :export
      get :warning
    end
  end

  resources :project_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end


  resources :warning_dbs, only: [:index, :update] do
    collection do
      get :match
      get :match_page
    end
  end

  resources :warning_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :project_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :stock_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :stock_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :mapping_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :mapping_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :users, except: [:new, :show] do
    collection do
      get :admin_new
      post :admin_create
    end
    member do
      patch :admin_update
    end
  end

  post 'sessions/login' => 'sessions#create'
  post 'sessions/visit' => 'sessions#visit'
  delete 'sessions/logout' => 'sessions#destroy'
  delete 'sessions/visit_out' => 'sessions#destroy_visit'
  get 'homes/get_warnings' => 'homes#get_warnings'


end

app/models/stock_db.rb
class StockDb < ActiveRecord::Base

  def self.search(params)

    @result=StockDb.where('stock_dbs.complete_time LIKE ?', "%#{params[:complete_time]}%")
                .where('stock_dbs.client_name LIKE ?', "%#{params[:client_name]}%")
                .where('stock_dbs.product_name LIKE ?', "%#{params[:product_name]}%")
                .where('stock_dbs.product_code LIKE ?', "%#{params[:product_code]}%")
                .where('stock_dbs.standard LIKE ?', "%#{params[:standard]}%")
                .where('stock_dbs.kind LIKE ?', "%#{params[:kind]}%")
                .where('stock_dbs.project_name LIKE ?', "%#{params[:project_name]}%")
                .where('stock_dbs.project_code LIKE ?', "%#{params[:project_code]}%")
                .where('stock_dbs.supplier LIKE ?', "%#{params[:supplier]}%")

    @result=@result.where('stock_dbs.export_num = ?', params[:export_num]) if !params[:export_num].blank?
    return @result
  end

  def self.filter_by_type(type)
    where("stock_dbs.supplier LIKE ?", "%#{type}%")
  end

end

app/controllers/stock_dbs_controller.rb
class StockDbsController < ApplicationController

  before_action :login

  def index
    if logged_in_visit?
      @stock_dbs=StockDb.filter_by_type(current_visit.supplier2).search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    elsif logged_in?
      @stock_dbs=StockDb.search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    else
      redirect_to root_path, flash: {:danger => "Error: 请联系开发人员"}
    end
  end

  def export
    if logged_in_visit?
      @stock_dbs=StockDb.filter_by_type(current_visit.supplier2).search(search_params)
    elsif logged_in?
      @stock_dbs=StockDb.search(search_params)
    end
    render xlsx: "出库数据_#{DateTime.now}", template: "stock_dbs/export.xlsx.axlsx"
  end

  private

  def search_params
    params
  end

  def login
    if current_user.nil? && current_visit.nil?
      redirect_to root_path, flash: {:danger => "请先登陆"}
    end
  end

end

app/views/stock_dbs/_stock_db.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-truck fa-fw"></i> 出库纪录
    <div class="pull-right">
      <%= form_tag export_stock_dbs_path, :method => :get do %>
          <%= hidden_field_tag :complete_time, params[:complete_time] %>
          <%= hidden_field_tag :client_name, params[:client_name] %>
          <%= hidden_field_tag :product_code, params[:product_code] %>
          <%= hidden_field_tag :product_name, params[:product_name] %>
          <%= hidden_field_tag :standard, params[:standard] %>
          <%= hidden_field_tag :kind, params[:kind] %>
          <%= hidden_field_tag :supplier, params[:supplier] %>
          <%= hidden_field_tag :export_num, params[:export_num] %>
          <%= hidden_field_tag :project_code, params[:project_code] %>
          <%= hidden_field_tag :project_name, params[:project_name] %>
          <%= button_tag(type: "submit", class: "btn btn-success btn-xs") do %>
              <span class="glyphicon glyphicon-floppy-save"></span> 导出
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="filter-panel">
    <%= form_tag stock_dbs_path, remote: true, :method => 'get', role: 'form', class: "form-inline" do %>

        <div class="form-group">
          <%= label_tag :client_name, "分公司" %>
          <%= text_field_tag :client_name, params[:client_name], placeholder: "输入分公司名称", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :product_code, "物料编码" %>
          <%= text_field_tag :product_code, params[:product_code], placeholder: "输入物料编码", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :product_name, "物料名称" %>
          <%= text_field_tag :product_name, params[:product_name], placeholder: "输入物料名称", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :standard, "规格型号" %>
          <%= text_field_tag :standard, params[:standard], placeholder: "输入规格", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :kind, "物资类别" %>
          <%= text_field_tag :kind, params[:kind], placeholder: "输入铁塔物资类别", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :supplier, "供应商" %>
          <%= text_field_tag :supplier, params[:supplier], placeholder: "输入供应商", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :export_num, "发货数量" %>
          <%= text_field_tag :export_num, params[:export_num], placeholder: "输入发货数量", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :project_name, "项目名称" %>
          <%= text_field_tag :project_name, params[:project_name], placeholder: "输入发货数量", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :project_code, "项目编号" %>
          <%= text_field_tag :project_code, params[:project_code], placeholder: "输入发货数量", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :complete_time, "出库日期" %>
          <%= text_field_tag :complete_time, params[:complete_time], placeholder: "输入发货完成时间", class: 'form-control input-sm' %>
        </div>

        <%= button_tag(type: "submit", class: "btn btn-info btn-sm", id: "filter-button") do %>
            <i class="fa fa-search"></i> 查找
        <% end %>

        <%= link_to stock_dbs_path, class: "btn btn-sm btn-warning", id: "filter-link", remote: true do %>
            <i class="fa fa-refresh"></i> 重置
        <% end %>

    <% end %>
    </br>

    <text class="text-muted">总数据
      <mark><%= @stock_dbs.count %></mark>
      条,当前页显示:
      <mark><%= @stock_dbs.length %></mark>
      条
    </text>

    <div class="pull-right">
      <%= will_paginate @stock_dbs, :param_name => 'page',
                        :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>
    </div>
  </div>
  <div class="panel-body" style="min-height:750px">
    <table class="table table-responsive table-condensed table-hover" id="small-table">
      <thead>
      <tr>
        <th>ID</th>
        <th class="col-md-1">分公司</th>
        <th class="col-md-1">物料代码</th>
        <th class="col-md-2">物料名称</th>
        <th class="col-md-1">规格型号</th>
        <th class="col-md-1">物资类别</th>
        <th>数量</th>
        <th class="col-md-2">项目名称</th>
        <th class="col-md-1" style="word-wrap: break-word">项目编号</th>
        <th class="col-md-1">出库时间</th>
        <th class="col-md-1">供应商</th>
      </tr>
      </thead>

      <tbody>

      <% count=0 %>
      <% @stock_dbs.each do |dbs| %>
          <% count= count+1 %>
          <tr>
            <td>
              <% if params[:page].nil? %>
                  <%= count %>
              <% else %>
                  <%= count+(params[:page].to_i-1)*20 %>
              <% end %>
            </td>
            <td>
              <%= dbs.client_name %>
            </td>
            <td>
              <%= dbs.product_code %>
            </td>
            <td>
              <%= dbs.product_name %>
            </td>
            <td>
              <%= dbs.standard %>
            </td>
            <td>
              <%= dbs.kind %>
            </td>
            <td>
              <%= dbs.export_num %>
            </td>
            <td>
              <%= dbs.project_name %>
            </td>
            <td>
              <%= dbs.project_code %>
            </td>
            <td>
              <%= dbs.complete_time %>
            </td>
            <td>
              <%= dbs.supplier %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stock_dbs/index.html.erb
<div class="sort_paginate_ajax">
  <%= render 'stock_db' %>
</div>

app/views/stock_dbs/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("stock_db"))%>")