config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'


  resources :supplier_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :supplier_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :repertory_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :repertory_dbs, only: [:index, :update] do
    collection do
      get :export
      get :warning
    end
  end

  resources :project_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end


  resources :warning_dbs, only: [:index, :update] do
    collection do
      get :match
      get :match_page
    end
  end

  resources :warning_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :project_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :stock_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :stock_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :mapping_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :mapping_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :users, except: [:new, :show] do
    collection do
      get :admin_new
      post :admin_create
    end
    member do
      patch :admin_update
    end
  end

  post 'sessions/login' => 'sessions#create'
  post 'sessions/visit' => 'sessions#visit'
  delete 'sessions/logout' => 'sessions#destroy'
  delete 'sessions/visit_out' => 'sessions#destroy_visit'
  get 'homes/get_warnings' => 'homes#get_warnings'


end

app/models/user.rb
class User < ActiveRecord::Base

  before_save   :downcase_email
  attr_accessor :remember_token
  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  #1. The ability to save a securely hashed password_digest attribute to the database
  #2. A pair of virtual attributes (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
  #3. An authenticate method that returns the user when the password is correct (and false otherwise)
  has_secure_password
  # has_secure_password automatically adds an authenticate method to the corresponding model objects.
  # This method determines if a given password is valid for a particular user by computing its digest and comparing the result to password_digest in the database.

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def self.filter_by_type(type)
    User.where("role = :type",type: type)
  end

  def self.none_hidden_users
    User.where("hidden = :type",type: false)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def user_remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def user_forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def user_authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private

  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :logged_in, only: :update
  before_action :correct_user, only: :update
  before_action :admin_logged_in, only: [:admin_update, :index, :destroy, :admin_create]

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, flash: {success: "新账号注册成功,请登陆"}
    else
      flash[:warning] = "账号信息填写有误,请重试"
      render 'new'
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash={:info => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to root_path, flash: flash
  end

  # -------------------------------------- admin

  def index
    @users=User.none_hidden_users.paginate(:page => params[:users_page], :per_page => 10)
    if !params[:user_id].blank?
      @user=User.find_by(id: params[:user_id].to_i)
    end
  end

  def admin_new
    @user=User.new
  end

  def admin_update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash[:info]="更新成功"
      if @user.id!=current_user.id
        if params[:user][:admin]=="管理员"
          @user.update_attribute(:admin, true)
        elsif params[:user][:admin]=="普通"
          @user.update_attribute(:admin, false)
        end
      end
    else
      flash[:warning]="更新失败"
    end
    redirect_to users_path
  end

  def admin_create
    @user = User.new(user_params)
    @user.admin=true if params[:user][:admin]=="管理员"
    @user.admin=false if params[:user][:admin]=="普通"
    if @user.save
      redirect_to users_path, flash: {:info => "创建成功"}
    else
      flash[:warning]= "创建失败"
      render 'admin_new'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_path(user_new: false), flash: {success: "用户删除"}
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :company, :password,
                                 :password_confirmation)
  end

  # Confirms a logged-in user.
  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def admin_logged_in
    unless admin?(current_user)
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_url, flash: {:warning => '此操作需要管理员身份'}
    end
  end


end

app/views/users/_admin_new_ajax.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-users fa-fw"></i> 用户管理
  </div>

  <div class="panel-body">
    <h4 class="text-muted">增加新用户</h4>
    <div class="alert alert-success">
      <br>
      <%= form_for User.new, url: admin_create_users_path, method: :post, html: {class: 'form', role: 'form'} do |f| %>
          <%= render 'shared/error_messages', :object => @user %>

          <div class="row">
            <div class="form-group col-sm-5">
              <%= f.label "姓名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "用户名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
              </div>
            </div>


            <div class="form-group col-sm-5">
              <%= f.label "公司名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
                <%= f.text_field :company, class: 'form-control', placeholder: "输入公司全称" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "角色", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-eye-open"></span></div>
                <%= f.select :admin, ['管理员', '普通'], {}, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "密码", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "确认密码", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
              </div>
            </div>

            <div class="col-sm-12">
              <%= f.submit '创建', class: "btn btn-success" %>
              <%= link_to "返回", users_path, method: :get, class: "btn btn-primary" %>
            </div>

          </div>

      <% end %>
    </div>

  </div>
</div>

app/views/users/_edit_user.html.erb
<div class="alert alert-success">
  <h4 class="text-muted">修改用户信息</h4>
  <br>

  <%= form_for @user, url: admin_update_user_path(@user), html: {class: 'form', role: 'form'} do |f| %>
      <%= render 'shared/error_messages', :object => @user %>

      <div class="row">
        <div class="form-group col-sm-5">
          <%= f.label "姓名", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
            <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
          </div>
        </div>

        <div class="form-group col-sm-5">
          <%= f.label "用户名", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
            <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
          </div>
        </div>


        <div class="form-group col-sm-5">
          <%= f.label "公司名", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
            <%= f.text_field :company, class: 'form-control', placeholder: "输入公司全称" %>
          </div>
        </div>

        <div class="form-group col-sm-5">
          <%= f.label "角色", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-eye-open"></span></div>
            <% if @user.admin %>
                <%= f.select :admin, options_for_select(['管理员', '普通']), {}, class: 'form-control' %>
            <% else %>
                <%= f.select :admin, options_for_select(['普通', '管理员']), {}, class: 'form-control' %>
            <% end %>

          </div>
        </div>

        <div class="form-group col-sm-5">
          <%= f.label "密码", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
            <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
          </div>
        </div>

        <div class="form-group col-sm-5">
          <%= f.label "确认密码", class: 'control-label' %>
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
          </div>
        </div>

        <div class="col-sm-12">
          <%= f.submit '保存修改', class: "btn btn-success" %>
        </div>
      </div>

  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <%= render 'shared/error_messages', :object => @user %>

    <div class="form-group">
      <%= f.label "姓名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
          <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "用户名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
          <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "公司名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
          <%= f.text_field :company, class: 'form-control', placeholder: "输入公司全称" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "密码", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
          <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "确认密码", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
        </div>
      </div>
    </div>

    <%= f.submit '注册', class: "btn btn-primary btn-block" %>
    <%= link_to '取消', root_path, :class => "btn btn-default btn-block" %>

<% end %>

app/views/users/_user_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-users fa-fw"></i> 用户管理
  </div>
  <div class="panel-body" style="min-height: 450px">
    <h4 class="text-muted">所有用户</h4>

    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>姓名</th>
        <th>邮箱</th>
        <th>公司</th>
        <th>角色</th>
        <th>注册时间</th>
        <th></th>

      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.company %></td>
            <% if user.admin %>
                <td>管理员</td>
            <% else %>
                <td>普通</td>
            <% end %>
            <td><%= user.created_at.strftime("%Y/%m/%d") %></td>

            <% if !params[:users_page].blank? %>
                <td><%= link_to "编辑", users_path(user_id: user.id, users_page: params[:users_page].to_i), remote: true, class: 'btn-sm btn-info' %></td>
            <% else %>
                <td><%= link_to "编辑", users_path(user_id: user.id), remote: true, class: 'btn-sm btn-info' %></td>
            <% end %>
            <td><%= link_to "删除", user_path(user), method: :delete, class: 'btn-sm btn-danger' %></td>

          </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @users, :param_name => 'users_page',
                      :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>

    <hr>

    <% if !params[:user_id].blank? &&!@user.nil? %>
        <%= render 'edit_user' %>
    <% end %>

  </div>
</div>

app/views/users/_user_new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-users fa-fw"></i> 用户管理
  </div>

  <div class="panel-body">
    <h4 class="text-muted">增加新用户</h4>
    <div class="alert alert-success">
      <br>
      <%= form_for User.new, url: admin_create_users_path, method: :post, html: {class: 'form', role: 'form'} do |f| %>

          <div class="row">
            <div class="form-group col-sm-5">
              <%= f.label "姓名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "用户名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
              </div>
            </div>


            <div class="form-group col-sm-5">
              <%= f.label "公司名", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
                <%= f.text_field :company, class: 'form-control', placeholder: "输入公司全称" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "角色", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-eye-open"></span></div>
                <%= f.select :admin, ['管理员', '普通'], {}, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "密码", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>

            <div class="form-group col-sm-5">
              <%= f.label "确认密码", class: 'control-label' %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
              </div>
            </div>

            <div class="col-sm-12">
              <%= f.submit '创建', class: "btn btn-success" %>
              <%= link_to "返回", users_path, method: :get, class: "btn btn-primary" %>
            </div>

          </div>

      <% end %>
    </div>

  </div>
</div>

app/views/users/admin_new.html.erb
<div class="sort_paginate_ajax">
  <%= render 'admin_new_ajax' %>
</div>

app/views/users/admin_new.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("admin_new_ajax"))%>")

app/views/users/index.html.erb
<div class="sort_paginate_ajax">
  <%= render 'user_index' %>
</div>

app/views/users/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("user_index"))%>")