config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'


  resources :supplier_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :supplier_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :repertory_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :repertory_dbs, only: [:index, :update] do
    collection do
      get :export
      get :warning
    end
  end

  resources :project_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end


  resources :warning_dbs, only: [:index, :update] do
    collection do
      get :match
      get :match_page
    end
  end

  resources :warning_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :project_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :stock_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :stock_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :mapping_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :mapping_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :users, except: [:new, :show] do
    collection do
      get :admin_new
      post :admin_create
    end
    member do
      patch :admin_update
    end
  end

  post 'sessions/login' => 'sessions#create'
  post 'sessions/visit' => 'sessions#visit'
  delete 'sessions/logout' => 'sessions#destroy'
  delete 'sessions/visit_out' => 'sessions#destroy_visit'
  get 'homes/get_warnings' => 'homes#get_warnings'


end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_excel_list.html.erb
<div id="content">
  <h4 class="text-muted">数据管理</h4>
  <hr>
  <% if params[:controller]=="stock_excels" %>

      <div class="alert alert-warning pull-right">
        目前出库数据的行数: <%= StockDb.all.size %>行
        <%= link_to clean_stock_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>

  <% elsif params[:controller]=="repertory_excels" %>
      <div class="alert alert-warning pull-right">
        目前库存数据的行数: <%= RepertoryDb.all.size %>行
        <%= link_to clean_repertory_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>

  <% elsif params[:controller]=="project_excels" %>
      <div class="alert alert-warning pull-right">
        目前立项数据的行数: <%= ProjectDb.all.size %>行
        <%= link_to clean_project_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>


  <% elsif params[:controller]=="mapping_excels" %>
      <div class="alert alert-warning pull-right">
        目前映射数据的行数: <%= MappingDb.all.size %>行
        <%= link_to clean_mapping_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>

  <% elsif params[:controller]=="supplier_excels" %>
      <div class="alert alert-warning pull-right">
        目前供应商数据的行数: <%= SupplierDb.all.size %>行
        <%= link_to clean_supplier_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>

  <% elsif params[:controller]=="warning_excels" %>
      <div class="alert alert-warning pull-right">
        目前安全阈值数据的行数: <%= WarningDb.all.size %>行
        <%= link_to clean_warning_excels_path, :remote => true, :data => {confirm: '确定清空数据?'}, class: 'btn-sm btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span> 清空数据
        <% end %>
      </div>
  <% end %>

  <%= form_for new_excel, url: path, html: {multipart: true} do |f| %>
      <%= f.file_field :file, title: "选择文件", accept: 'application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>
      <%= button_tag(type: "submit", class: "btn btn-info") do %>
          <span class="glyphicon glyphicon-cloud-upload"></span> 上传
      <% end %>
  <% end %>

  <small class="bg-warning">注意: Excel文件的行数不要超过1500,文件过大会造成服务器崩溃</small>

  <br>

  <table class="table table-responsive table-condensed table-hover">

    <tr>
      <th>文件</th>
      <th>上传时间</th>
      <th>文件大小</th>
      <th></th>
      <th></th>
      <th></th>

    </tr>
    <tbody>
    <% excels.each do |excel| %>
        <tr>
          <td><span class="	glyphicon glyphicon-link"></span>
            <%= excel.file_file_name %>
          </td>
          <td>
            <%= excel.file_updated_at.strftime("%Y/%m/%d %H:%M") if !excel.file_updated_at.nil? %>
          </td>
          <td>
            <%= number_to_human_size(excel.file_file_size) %>
          </td>

          <td><%= link_to '下载', excel.file.url(:original, false), class: 'btn-xs btn-success pull-right' %></td>

          <% if params[:controller]=="stock_excels" %>
              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_stock_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>
          <% elsif params[:controller]=="repertory_excels" %>
              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_repertory_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>
          <% elsif params[:controller]=="project_excels" %>
              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_project_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>
          <% elsif params[:controller]=="supplier_excels" %>

              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_supplier_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>

          <% elsif params[:controller]=="mapping_excels" %>
              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_mapping_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>
          <% elsif params[:controller]=="warning_excels" %>
              <% if excel.parse %>
                  <td>
                    <button type="button" class="btn btn-xs pull-right disabled">已解析</button>
                  </td>
              <% else %>
                  <td><%= link_to '解析', parse_warning_excel_path(excel), remote: true, class: 'btn-xs btn-primary pull-right' %></td>
              <% end %>
          <% end %>

          <% if params[:controller]=="stock_excels" %>
              <td><%= link_to '删除', stock_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
          <% elsif params[:controller]=="repertory_excels" %>
              <td><%= link_to '删除', repertory_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
          <% elsif params[:controller]=="project_excels" %>
              <td><%= link_to '删除', project_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
          <% elsif params[:controller]=="supplier_excels" %>
              <td><%= link_to '删除', supplier_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
          <% elsif params[:controller]=="mapping_excels" %>
              <td><%= link_to '删除', mapping_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
          <% elsif params[:controller]=="warning_excels" %>
              <td><%= link_to '删除', warning_excel_path(excel), method: :delete, :data => {confirm: '确定删除?'}, class: 'btn-xs btn-danger pull-right' %></td>
        <% end %>

        </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate excels, :param_name => 'excel_page',
                    :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>

</div>

<script type="text/javascript">
    $('input[type=file]').bootstrapFileInput();
    $('.file-inputs').bootstrapFileInput();
</script>

<%= render "shared/spanner" %>

app/views/shared/_spanner.html.erb
<!--<div class="spanner" style="background: #1abc9c; height: 100%">-->
<div class="sk-wave" style="margin-top: 100px">
  <div style="font-size: 15px">处理中</div>
  <div class="sk-rect sk-rect1"></div>
  <div class="sk-rect sk-rect2"></div>
  <div class="sk-rect sk-rect3"></div>
  <div class="sk-rect sk-rect4"></div>
  <div class="sk-rect sk-rect5"></div>
</div>
<!--</div>-->

<script>
  $(document).ready(function () {

    $(".sk-wave").hide();
    // show spinner on AJAX start
    $(document).ajaxStart(function () {
      $(".sk-wave").show();
      $("#content").hide();
    });

    // hide spinner on AJAX stop
    $(document).ajaxStop(function () {
      $("#content").show();
      $(".sk-wave").hide();
    });

  });
</script>