config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'


  resources :supplier_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :supplier_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :repertory_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :repertory_dbs, only: [:index, :update] do
    collection do
      get :export
      get :warning
    end
  end

  resources :project_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end


  resources :warning_dbs, only: [:index, :update] do
    collection do
      get :match
      get :match_page
    end
  end

  resources :warning_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :project_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :stock_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :stock_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :mapping_excels, only: [:index, :destroy, :create] do
    collection do
      get :clean
    end
    member do
      get :parse
    end
  end

  resources :mapping_dbs, only: :index do
    collection do
      get :export
    end
  end

  resources :users, except: [:new, :show] do
    collection do
      get :admin_new
      post :admin_create
    end
    member do
      patch :admin_update
    end
  end

  post 'sessions/login' => 'sessions#create'
  post 'sessions/visit' => 'sessions#visit'
  delete 'sessions/logout' => 'sessions#destroy'
  delete 'sessions/visit_out' => 'sessions#destroy_visit'
  get 'homes/get_warnings' => 'homes#get_warnings'


end

app/models/repertory_db.rb
class RepertoryDb < ActiveRecord::Base

  def self.search(params)
    where('repertory_dbs.name LIKE ?', "%#{params[:name]}%")
        .where('repertory_dbs.standard LIKE ?', "%#{params[:standard]}%")
        .where('repertory_dbs.supplier LIKE ?', "%#{params[:supplier]}%")
        .where('repertory_dbs.product_code LIKE ?', "%#{params[:product_code]}%")
        .where('repertory_dbs.product_kind LIKE ?', "%#{params[:product_kind]}%")
        .where('repertory_dbs.model LIKE ?', "%#{params[:model]}%")
  end

  # def self.filter_by_type(type)
  #   where("supplier = :type", type: type)
  # end

  def self.filter_by_type(type)
    where("repertory_dbs.supplier LIKE ?", "%#{type}%")
  end

  def self.filter_by_num
    where("repertory_dbs.safe_num IS NOT NULL AND repertory_dbs.safe_num >= repertory_dbs.available")
  end

end

app/controllers/repertory_dbs_controller.rb
class RepertoryDbsController < ApplicationController

  before_action :login

  def index
    if logged_in_visit?
      @repertory_dbs=RepertoryDb.filter_by_type(current_visit.supplier2).search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    elsif logged_in?
      @repertory_dbs=RepertoryDb.search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    else
      redirect_to root_path, flash: {:danger => "Error: 请联系开发人员"}
    end
  end

  def warning
    if logged_in_visit?
      @repertory_dbs=RepertoryDb.filter_by_num.filter_by_type(current_visit.supplier2).search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    elsif logged_in?
      @repertory_dbs=RepertoryDb.filter_by_num.search(search_params).order('created_at desc').paginate(:page => params[:page], :per_page => 20)
    else
      redirect_to root_path, flash: {:danger => "Error: 请联系开发人员"}
    end
  end

  def update
    @repertory_data = RepertoryDb.find_by_id(params[:id])
    @repertory_data.update_attributes(repertory_params)
    redirect_to warning_repertory_dbs_path(page: params[:page])
  end

  def export
    if logged_in_visit?
      @repertory_dbs=RepertoryDb.filter_by_type(current_visit.supplier2).search(search_params)
    elsif logged_in?
      @repertory_dbs=RepertoryDb.search(search_params)
    end
    render xlsx: "库存数据_#{DateTime.now}", template: "repertory_dbs/export.xlsx.axlsx"
  end

  private
  def search_params
    params
  end

  def login
    if current_user.nil? && current_visit.nil?
      redirect_to root_path, flash: {:danger => "请先登陆"}
    end
  end

  def repertory_params
    params.require(:repertory_db).permit(:safe_num, :common_num)
  end

end

app/views/repertory_dbs/_repertory_db.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-cubes fa-fw"></i> 库存明细
    <div class="pull-right">
      <%= form_tag export_repertory_dbs_path, :method => :get do %>
          <%= hidden_field_tag :name, params[:name] %>
          <%= hidden_field_tag :supplier, params[:supplier] %>
          <%= hidden_field_tag :standard, params[:standard] %>
          <%= hidden_field_tag :product_code, params[:product_code] %>
          <%= hidden_field_tag :product_kind, params[:product_kind] %>
          <%= hidden_field_tag :model, params[:model] %>
          <%= button_tag(type: "submit", class: "btn btn-success btn-xs") do %>
              <span class="glyphicon glyphicon-floppy-save"></span> 导出
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="filter-panel">
    <%= form_tag repertory_dbs_path, :method => 'get', remote: true, role: 'form', class: "form-inline" do %>
        <div class="form-group">
          <%= label_tag :name, "产品:" %>
          <%= text_field_tag :name, params[:name], placeholder: "产品", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :standard, "规格:" %>
          <%= text_field_tag :standard, params[:standard], placeholder: "规格", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :model, "型号:" %>
          <%= text_field_tag :model, params[:model], placeholder: "型号", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :supplier, "供应商:" %>
          <%= text_field_tag :supplier, params[:supplier], placeholder: "供应商", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :product_code, "物料代码:" %>
          <%= text_field_tag :product_code, params[:product_code], placeholder: "物料编码", class: 'form-control input-sm' %>
        </div>

        <div class="form-group">
          <%= label_tag :product_kind, "物资类别:" %>
          <%= text_field_tag :product_kind, params[:product_kind], placeholder: "物资类别", class: 'form-control input-sm' %>
        </div>

        <%= button_tag(type: "submit", class: "btn btn-info btn-sm", id: "filter-button") do %>
            <i class="fa fa-search"></i> 查找
        <% end %>

        <%= link_to repertory_dbs_path, class: "btn btn-sm btn-warning", id: "filter-link", remote: true do %>
            <i class="fa fa-refresh"></i> 重置
        <% end %>

    <% end %>
    </br>

    <text class="text-muted">总数据
      <mark><%= @repertory_dbs.count %></mark>
      条,当前页显示:
      <mark><%= @repertory_dbs.length %></mark>
      条
    </text>

    <div class="pull-right">
      <%= will_paginate @repertory_dbs, :param_name => 'page',
                        :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>
    </div>
  </div>

  <div class="panel-body" style="min-height:750px">
    <table class="table table-responsive table-condensed table-hover" id="small-table">
      <thead>
      <tr>
        <th>ID</th>
        <th class="col-md-1">物料代码</th>
        <th class="col-md-2">产品</th>
        <th class="col-md-2">规格</th>
        <th class="col-md-1">型号</th>
        <th class="col-md-1">库存数量</th>
        <th class="col-md-1">可用数量</th>
        <th class="col-md-1">单位</th>
        <th class="col-md-2">供应商</th>
        <th class="col-md-1">物资类别</th>
        <th class="col-md-1">应有</th>
      </tr>
      </thead>

      <tbody>

      <% count=0 %>
      <% @repertory_dbs.each do |repertory| %>
          <% count= count+1 %>
          <tr>
            <td>
              <% if params[:page].nil? %>
                  <%= count %>
              <% else %>
                  <%= count+(params[:page].to_i-1)*20 %>
              <% end %>
            </td>
            <td>
              <%= repertory.product_code %>
            </td>
            <td>
              <%= repertory.name %>
            </td>
            <td>
              <%= repertory.standard %>
            </td>
            <td>
              <%= repertory.model %>
            </td>
            <td>
              <%= repertory.num %>
            </td>
            <td>
              <%= repertory.available %>
            </td>
            <td>
              <%= repertory.unit %>
            </td>
            <td>
              <%= repertory.supplier %>
            </td>
            <td>
              <%= repertory.product_kind %>
            </td>
            <td>
              <%= repertory.safe_num %>
            </td>
          </tr>
      <% end %>

      </tbody>
    </table>
  </div>

  <%#= render 'shared/spanner' %>
</div>

app/views/repertory_dbs/_repertory_warning.html.erb
<% if request.xhr? %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong> <%= message %></strong>
        </div>
    <% end %>
<% end %>

<div id="content">
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-cubes fa-fw"></i> 库存提醒
    </div>

    <div class="filter-panel">
      <%= form_tag warning_repertory_dbs_path, :method => 'get', remote: true, role: 'form', class: "form-inline" do %>
          <div class="form-group">
            <%= label_tag :name, "产品:" %>
            <%= text_field_tag :name, params[:name], placeholder: "产品", class: 'form-control input-sm' %>
          </div>

          <div class="form-group">
            <%= label_tag :standard, "规格:" %>
            <%= text_field_tag :standard, params[:standard], placeholder: "规格", class: 'form-control input-sm' %>
          </div>

          <div class="form-group">
            <%= label_tag :model, "型号:" %>
            <%= text_field_tag :model, params[:model], placeholder: "型号", class: 'form-control input-sm' %>
          </div>

          <div class="form-group">
            <%= label_tag :supplier, "供应商:" %>
            <%= text_field_tag :supplier, params[:supplier], placeholder: "供应商", class: 'form-control input-sm' %>
          </div>

          <div class="form-group">
            <%= label_tag :product_code, "物料代码:" %>
            <%= text_field_tag :product_code, params[:product_code], placeholder: "物料编码", class: 'form-control input-sm' %>
          </div>

          <div class="form-group">
            <%= label_tag :product_kind, "物资类别:" %>
            <%= text_field_tag :product_kind, params[:product_kind], placeholder: "物资类别", class: 'form-control input-sm' %>
          </div>

          <%= button_tag(type: "submit", class: "btn btn-info btn-sm", id: "filter-button") do %>
              <i class="fa fa-search"></i> 查找
          <% end %>

          <%= link_to warning_repertory_dbs_path, class: "btn btn-sm btn-warning", id: "filter-link", remote: true do %>
              <i class="fa fa-refresh"></i> 重置
          <% end %>

      <% end %>
      </br>

      <text class="text-muted">总数据
        <mark><%= @repertory_dbs.count %></mark>
        条,当前页显示:
        <mark><%= @repertory_dbs.length %></mark>
        条
      </text>

      <div class="pull-right">
        <%= will_paginate @repertory_dbs, :param_name => 'page',
                          :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>
      </div>
    </div>

    <div class="panel-body" style="min-height:750px">
      <table class="table table-responsive table-condensed table-hover" id="small-table">
        <thead>
        <tr>
          <th>ID</th>
          <th>物料代码</th>
          <th>产品</th>
          <th>规格</th>
          <th>型号</th>
          <th>库存数量</th>
          <th>可用数量</th>
          <th>单位</th>
          <th>供应商</th>
          <th>物资类别</th>
          <th>安全库存值</th>
          <th>常用库存值</th>
          <th>应补货数量</th>
        </tr>
        </thead>

        <tbody>

        <% count=0 %>
        <% @repertory_dbs.each do |repertory| %>
            <% count= count+1 %>
            <tr>
              <td>
                <% if params[:page].nil? %>
                    <%= count %>
                <% else %>
                    <%= count+(params[:page].to_i-1)*20 %>
                <% end %>
              </td>
              <td>
                <%= repertory.product_code %>
              </td>
              <td>
                <%= repertory.name %>
              </td>
              <td>
                <%= repertory.standard %>
              </td>
              <td>
                <%= repertory.model %>
              </td>
              <td>
                <%= repertory.num %>
              </td>
              <td>
                <%= repertory.available %>
              </td>
              <td>
                <%= repertory.unit %>
              </td>
              <td>
                <%= repertory.supplier %>
              </td>
              <td>
                <%= repertory.product_kind %>
              </td>

              <% if !current_visit %>
                  <td>
                    <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#Modal-<%= repertory.id %>"><%= repertory.safe_num %>
                    </button>
                  </td>

                  <td>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#Modal-<%= repertory.id %>"><%= repertory.common_num %>
                    </button>
                  </td>

                  <td>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#Modal-<%= repertory.id %>"><%= repertory.common_num-repertory.available %>
                    </button>
                  </td>

                  <div id="Modal-<%= repertory.id %>" class="modal fade" role="dialog">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                        <div class="modal-body">
                          <%= form_for repertory, url: repertory_db_url(repertory) do |f| %>
                              <div class="form-group">
                                <label>修改安全库存值：</label>
                                <%= f.text_field :safe_num, class: "form-control input-sm" %>
                              </div>
                              <div class="form-group">
                                <label>修改常用库存值：</label>
                                <%= f.text_field :common_num, class: "form-control input-sm" %>
                              </div>
                              <hr>
                              <%= f.submit '确定', class: "btn btn-info btn-sm" %>
                              <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">取消</button>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
              <% else %>
                  <td>
                    <%= repertory.safe_num %>
                  </td>
                  <td>
                    <%= repertory.common_num %>
                  </td>
                  <td>
                    <%= repertory.common_num-repertory.available %>
                  </td>
              <% end %>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>

  </div>
</div>

<%= render "shared/spanner" %>

app/views/repertory_dbs/index.html.erb
<div class="sort_paginate_ajax">
  <%= render 'repertory_db' %>
</div>

app/views/repertory_dbs/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("repertory_db"))%>")

app/views/repertory_dbs/warning.html.erb
<div class="sort_paginate_ajax">
  <%= render 'repertory_warning' %>
</div>

app/views/repertory_dbs/warning.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("repertory_warning"))%>")